version: '3.8'

services:
  web:
    build: .
    container_name: msx-veiculos
    ports:
      - "9000:9000"
    environment:
      - USER_DB=marcelo123
      - PASSWORD_DB=123456
      - URL_DB=db
      - PORT_DB=3306
      - SCHEMA_DB=msx_veiculos
      - SECRET_KEY=1234teste
      - ALGORITHM=HS256
      - ERRO_401=Not authenticated
      - ERRO_404=Not found
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: msx_veiculos
      MYSQL_USER: marcelo123
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"  # Externo:Interno
    volumes:
      - db_data:/var/lib/mysql

    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1" ]  # Alterado para 127.0.0.1
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db_data:
